# Site settings
title: Kims Chao 博客
email: Kims.chao@gmail.com
description: > # 我的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kimschao.githuab.io" # the base hostname & protocol for your site
twitter_username: kimschao
github_username:  kimschao
highlighter: pygments

# Build settings
markdown: kramdown
